export const DateFormat = {
    dd_MM_yyyy: "DD/MM/YYYY",
    MM_dd_yyyy: "MM/dd/YYYY",
    dd_MMM_yyyy: "DD MMM, YYYY",
    MMMM_dd_yyyy: "MMMM DD, YYYY",
    dd_MMMM_yyyy: "DD MMMM, YYYY",
    MMMM_dd_yyyy_AT_hh_mm_a: "MMMM dd, YYYY @ hh:mm a",
    dd_MM_yyyy_HH_mm_ss: "DD/MM/YYYY HH:mm:ss",
    dd_MMMM_yyyy_hh_mm_ss: "DD MMMM,YYYY hh:mm:ss",
    dd_MM_yyyy_HH_mm: "DD/MM/YYYY HH:mm",
    HH_mm: "HH:mm",
    hh_mm_a: "hh:mm a",
    hh: "hh",
    mm: "mm",
    a: "a",
    HH: "HH",
    hh_mm_ss: "hh:mm:ss",
    MM_dd_yyyy_hh_mm_a: "MM/DD/YYYY hh:mm a",
    E_MM_DD: "EEEE MM/dd ",
    dd_MM_yyyy_hh_mm_a: "DD MMM, YYYY hh:mm a",
    dd_MMMM_yyyy_hh_mm_a: "DD MMMM, YYYY hh:mm a",
    dd: "DD"
};
